defmodule ImageManipulatorWeb.MediaController do
  @moduledoc """
  Serves image bytes to the browser: originals, generated thumbnails and
  downloads.

  The URL only carries a signed token (`/media/:token`), never a path. Tokens
  are minted by `ImageManipulator.Workspace` for files the app already decided
  the user may see, and are re-validated here against the readable roots, so a
  tampered token cannot be used to read arbitrary files.

  Requesting a token that carries a width returns a *real* scaled image: the
  thumbnail is generated by ImageMagick and cached on disk, rather than being
  resized by the browser.
  """

  use ImageManipulatorWeb, :controller

  alias ImageManipulator.Workspace

  @doc """
  Streams the file behind a media token.
  """
  def show(conn, %{"token" => token}) do
    case Workspace.verify_media(token) do
      {:ok, %{width: nil} = media} ->
        send_source(conn, media.path, media.download)

      {:ok, %{width: width} = media} ->
        case Workspace.thumbnail(media.path, width) do
          {:ok, thumb} -> send_source(conn, thumb, media.download)
          {:error, reason} -> fail(conn, 404, "Thumbnail unavailable: #{reason}")
        end

      {:error, reason} ->
        fail(conn, 403, reason)
    end
  end

  defp send_source(conn, path, download) do
    if File.regular?(path) do
      conn
      |> put_resp_content_type(MIME.from_path(path))
      |> put_resp_header("cache-control", "private, max-age=300")
      |> maybe_attachment(download, Path.basename(path))
      |> send_file(200, path)
    else
      fail(conn, 404, "That file is no longer on disk.")
    end
  end

  defp maybe_attachment(conn, nil, _fallback), do: conn

  defp maybe_attachment(conn, download, fallback) do
    filename = download |> to_string() |> safe_filename(fallback)
    put_resp_header(conn, "content-disposition", ~s(attachment; filename="#{filename}"))
  end

  # Keeps the header valid: quoted-string safe ASCII, never empty.
  defp safe_filename(name, fallback) do
    cleaned = String.replace(name, ~r/[^A-Za-z0-9._\- ]+/, "_")

    if cleaned == "", do: safe_filename(fallback, "download.jpg"), else: cleaned
  end

  defp fail(conn, status, message) do
    conn
    |> put_resp_content_type("text/plain")
    |> send_resp(status, message)
  end
end
